# Generated by Django 2.0.2 on 2018-02-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkey', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('dex_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreignkey.Person'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreignkey.Type'),
        ),
    ]
