# Generated by Django 2.0.2 on 2018-02-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_inheritance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artice',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='bookreview',
            old_name='artice_ptr',
            new_name='article_ptr',
        ),
    ]
